In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math

In [5]:
df = pd.read_csv("./data/50_Startups.csv")

df.head()

,Startup_Name,County,Sector,Year_Founded,Employees,R&D_Spend_KES,Administration_KES,Marketing_Spend_KES,Profit_KES,ROI
0,Tuko Trade,Nairobi,E-Commerce,2021,222,21495396.0,17796714.0,61331933.0,24994037.9,24.839032
1,Tuko Technologies,Mombasa,E-Commerce,2018,246,21137701.0,19679086.7,57706808.9,24932967.8,25.306595
2,Ujuzi Technologies,Kisumu,E-Commerce,2022,164,19947396.3,13148921.5,53031490.2,24836550.7,28.836855
3,Nairobi Innovations,Nakuru,E-Commerce,2019,193,18768413.3,15427340.5,49815950.6,23777258.7,28.302317
4,Equity Pay,Eldoret,E-Commerce,2021,149,18473954.2,11880930.1,47601894.6,21604432.2,27.713346


In [8]:
X = df[["R&D_Spend_KES", "Administration_KES", "Marketing_Spend_KES", "County"]].values  
#.values is converting dataframe into array
print(X)
y = df[["Profit_KES"]].values
print(y)

[[21495396.0 17796714.0 61331933.0 'Nairobi']
 [21137701.0 19679086.7 57706808.9 'Mombasa']
 [19947396.3 13148921.5 53031490.2 'Kisumu']
 [18768413.3 15427340.5 49815950.6 'Nakuru']
 [18473954.2 11880930.1 47601894.6 'Eldoret']
 [17143997.0 12975912.3 47171976.8 'Nairobi']
 [17500009.8 19135853.1 16603186.6 'Mombasa']
 [16938756.9 18918907.8 42103968.4 'Nairobi']
 [15670527.6 19333463.5 40509727.7 'Kisumu']
 [16033534.4 14128292.1 39647610.6 'Nakuru']
 [13248700.4 14377234.3 29790923.5 'Nairobi']
 [13087354.8 11932779.3 32466791.5 'Mombasa']
 [12202287.5 16551649.4 32479127.2 'Kisumu']
 [11959010.7 17614359.1 32846440.9 'Nairobi']
 [15592621.2 20351164.6 33346679.6 'Nakuru']
 [14888069.3 15940189.2 34030909.9 'Mombasa']
 [10141704.3 15807681.5 34364987.8 'Nairobi']
 [12305430.8 18860085.4 36734660.3 'Kisumu']
 [11927390.8 14842852.7 38339544.1 'Nairobi']
 [11234561.0 19956834.3 0.0 'Eldoret']
 [9913001.8 14802749.0 38826381.1 'Nairobi']
 [10190631.1 19990545.9 38965847.7 'Mombasa']
 [9

In [9]:
st = ColumnTransformer([("County", OneHotEncoder(), [3])], remainder = 'passthrough')
X = st.fit_transform(X)
print(X)

[[0.0 0.0 0.0 1.0 0.0 21495396.0 17796714.0 61331933.0]
 [0.0 0.0 1.0 0.0 0.0 21137701.0 19679086.7 57706808.9]
 [0.0 1.0 0.0 0.0 0.0 19947396.3 13148921.5 53031490.2]
 [0.0 0.0 0.0 0.0 1.0 18768413.3 15427340.5 49815950.6]
 [1.0 0.0 0.0 0.0 0.0 18473954.2 11880930.1 47601894.6]
 [0.0 0.0 0.0 1.0 0.0 17143997.0 12975912.3 47171976.8]
 [0.0 0.0 1.0 0.0 0.0 17500009.8 19135853.1 16603186.6]
 [0.0 0.0 0.0 1.0 0.0 16938756.9 18918907.8 42103968.4]
 [0.0 1.0 0.0 0.0 0.0 15670527.6 19333463.5 40509727.7]
 [0.0 0.0 0.0 0.0 1.0 16033534.4 14128292.1 39647610.6]
 [0.0 0.0 0.0 1.0 0.0 13248700.4 14377234.3 29790923.5]
 [0.0 0.0 1.0 0.0 0.0 13087354.8 11932779.3 32466791.5]
 [0.0 1.0 0.0 0.0 0.0 12202287.5 16551649.4 32479127.2]
 [0.0 0.0 0.0 1.0 0.0 11959010.7 17614359.1 32846440.9]
 [0.0 0.0 0.0 0.0 1.0 15592621.2 20351164.6 33346679.6]
 [0.0 0.0 1.0 0.0 0.0 14888069.3 15940189.2 34030909.9]
 [0.0 0.0 0.0 1.0 0.0 10141704.3 15807681.5 34364987.8]
 [0.0 1.0 0.0 0.0 0.0 12305430.8 18860085.4 3673

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [11]:
model = LinearRegression()
model.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [12]:
y_pred = model.predict(X_test)

In [13]:
#Comparison

print('- y_pred : ')
print(y_pred)
print('- y_test : ')
print(y_test)

- y_pred : 
[[13959279.80617867]
 [16665891.97928465]
 [17696633.34506147]
 [ 8853744.52620908]
 [23456512.62361097]
 [15450141.17575038]
 [ 8636287.25181697]
 [12433759.21468504]
 [15352387.49826607]
 [22111634.68589832]]
- y_test : 
[[13426709.4]
 [18753722. ]
 [18995853.5]
 [10113847.9]
 [24836550.7]
 [13651080.3]
 [10559777.8]
 [12672862.8]
 [14345792.5]
 [21604432.2]]


In [15]:
print(y_pred.sum().mean())
print(y_test.sum().mean())

print("So called Accuracy ", y_pred.sum().mean()/y_test.sum().mean())

154616272.10676163
158960629.1
So called Accuracy  0.9726702327624447
